name: CI
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      USE_IN_MEMORY: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Upload coverage report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: ignore

  # Optional future job for e2e or integration with real Judge0 (kept minimal for now)
  # judge0-integration:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Future Judge0 integration tests here"
